name: "Infrastructure CI/CD (Terraform)"

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write      # Obligatoire pour OIDC
  contents: read       # Pour lire le code
  security-events: write # Pour envoyer le rapport Trivy √† GitHub Security

jobs:
  terraform-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important pour SonarCloud

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # --- √âTAPE S√âCURIT√â : TRIVY ---
      - name: Run Trivy Security Scan (IaC) üõ°Ô∏è
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          format: 'sarif'
          output: 'trivy-infra-results.sarif'

      - name: Upload Trivy results to GitHub üì§
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-infra-results.sarif'

      # --- √âTAPE QUALIT√â : SONARCLOUD ---
      - name: SonarCloud Scan ‚òÅÔ∏è
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # --- √âTAPE D√âPLOIEMENT ---
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
